[tool.black]
line-length = 120
skip-string-normalization = true
include = '(src/tribler-gui|src/tribler-common|src/tribler-core/tribler_core/modules/metadata_store)/.*\.pyi?$'

exclude = '''
/(
    \.git
  | \.venv
  | \.idea 
  | snap
  | doc
)/
'''
